### PR TITLE
[1.x] Features: Allow HTML in buttons/tabs + Orderable tabs

### PR DESCRIPTION
**Pull request by caseydwyer**
Hey @jacksleight! 👋 I have a completely unsolicited addition for minisets; feel free to shoot this down. 🙂 Made of two parts:

## HTML in Buttons & Tabs
The first set of commits are pretty straightforward. They allow for HTML in the `value` of variants. This is useful for tab flexibility, especially in circumstances where space is tight—like many variants, or < full-width context. Could be used for a number of things (changing text color, casing, etc.) but my primary use-case is leveraging icons—SVG, FontAwesome, etc.—to save space.

eg, going from this, with normal `Label` values that sometimes get stacked in tight spaces...

nope

...to using HTML like `LG <i class="ml-1 text-lg fa-duotone fa-laptop"></i>` and getting...

yep

## Orderable Tabs
The second set of commits give users the ability, via the config of a miniset field, to "lock" the order of tabs. This makes a lot of sense, IMHO, for screen-size variants, where it's logical & useful to keep screen sizes in their proper order. This piece was obviously more involved, so I tried to put context into each commit.

Let me know if you have any questions or want to see any changes, and thanks for your consideration! Happy Friday!

### CODE REVIEW

**Comment by jacksleight** [comment]
Hey, thanks for the PR! Sounds good, I'll review it as soon as I can.

One thought, does the ordering even need to be configurable? Maybe the tab order should just always match the variant order. Seems logical and would make the implementation a bit simpler. What do you think?

**Comment by caseydwyer** [comment]
> One thought, does the ordering even need to be configurable? Maybe the tab order should just always match variant order.

Heh, great question. I think I was just assuming that might feel heavy-handed—didn't want to force it on people. But now that I stop to actually consider it, that's probably a logical default. I can't think of an instance where you would have variants set up (ie, anytime you're using the `Classes` fieldtype) and _**not**_ want to have them show in the order you configured them. I'm happy to make that adjustment, if you're good with making ordered the default—just let me know!

**Comment by jacksleight** [comment]
Yep let's go with that 👍

**Comment by caseydwyer** [comment]
Great, should be set!

**Comment by jacksleight** [comment]
Thanks again! I simplified it slightly by using `Array.sort` and tweaked the metadata.

**Comment by caseydwyer** [comment]
Good stuff, thanks for polishing that up!

**Pull request merged**
